apiVersion: v1
kind: Service
metadata:
  labels:
    app: examplenet8-aks
  name: examplenet8-aks
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: examplenet8-aks
    component: examplenet8-app
  type: LoadBalancer